# Need to change YOUR_CLUSTER, YOUR_API_TOKEN and YOUR_WAVEFRONT_URL accordingly
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
spec:
  collectorEnabled: true
  clusterName: YOUR_CLUSTER_NAME
  wavefrontProxyEnabled: true
  wavefrontTokenSecret: wavefront-secret
  wavefrontUrl: YOUR_WAVEFRONT_URL
