# Need to change YOUR_CLUSTER_NAME, YOUR_WAVEFRONT_URL accordingly
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: wavefront
spec:
  clusterName: YOUR_CLUSTER_NAME
  wavefrontUrl: YOUR_WAVEFRONT_URL
  dataCollection:
    metrics:
      enable: true
  dataExport:
    externalWavefrontProxy:
      url: https://localhost:8080
    wavefrontProxy:
      enable: false