# wavefront_namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: wavefront
---
# operator_service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wavefront-operator
  namespace: wavefront
---
# collector_service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wavefront-collector
  namespace: wavefront
---
# operator_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: wavefront-operator
  namespace: wavefront
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - wavefront-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - wavefront.com
  resources:
  - '*'
  - wavefrontproxies
  - wavefrontcollectors
  verbs:
  - '*'
---
# collector_cluster_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: null
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: wavefront-collector
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - nodes
  - nodes/stats
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
  - create
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- nonResourceURLs: ["/metrics"]
  verbs:
  - get
---
# operator_role_binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wavefront-operator
  namespace: wavefront
subjects:
- kind: ServiceAccount
  name: wavefront-operator
roleRef:
  kind: Role
  name: wavefront-operator
  apiGroup: rbac.authorization.k8s.io
---
# collector_cluster_role_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wavefront-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wavefront-collector
subjects:
- kind: ServiceAccount
  name: wavefront-collector
  namespace: wavefront
---
# wavefrontcollector_crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wavefrontcollectors.wavefront.com
spec:
  group: wavefront.com
  names:
    kind: WavefrontCollector
    listKind: WavefrontCollectorList
    plural: wavefrontcollectors
    singular: wavefrontcollector
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            configName:
              description: The name of the config map providing the configuration
                for the collector instance. If empty, a default name of "collectorName-config"
                is assumed.
              type: string
            daemon:
              description: Whether to deploy the collector as a daemonset. False will
                roll out as a deployment.
              type: boolean
            disableUpdate:
              description: Whether to disable automatically updating the collector
                if a new version becomes available.
              type: boolean
            enableDebug:
              description: Whether to enable debug logging and profiling
              type: boolean
            env:
              description: List of environment variables to set for the Collector
                containers.
              items:
                type: object
              type: array
            image:
              description: Defaults to wavefronthq/wavefront-kubernetes-collector:latest
              type: string
            resources:
              description: Compute resources required by the Collector containers.
              type: object
            tolerations:
              description: Tolerations for the collector pods
              items:
                type: object
              type: array
          type: object
        status:
          properties:
            updatedTimestamp:
              format: date-time
              type: string
            version:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
# wavefrontproxy_crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wavefrontproxies.wavefront.com
spec:
  group: wavefront.com
  names:
    kind: WavefrontProxy
    listKind: WavefrontProxyList
    plural: wavefrontproxies
    singular: wavefrontproxy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalPorts:
              description: The comma separated list of ports that need to be opened
                on Proxy Pod and Services. Needs to be explicitly specified when using
                "Advanced" configuration.
              type: string
            advanced:
              description: The name of the config map providing the advanced configurations
                for the Wavefront proxy.
              type: string
            histogramDistPort:
              description: The port to listen on for Wavefront histogram distribution
                formatted data. This is usually 40000
              format: int32
              type: integer
            image:
              description: The WavefrontProxy image to use. Defaults to wavefronthq/proxy:latest
              type: string
            jaegerPort:
              description: The port to listen on for Jaeger Thrift formatted data.
                Defaults to none. This is usually 30001
              format: int32
              type: integer
            metricPort:
              description: The port number the proxy will listen on for metrics in
                Wavefront data format. This is usually port 2878 by default.
              format: int32
              type: integer
            preprocessor:
              description: The name of the config map providing the preprocessor rules
                for the Wavefront proxy.
              type: string
            size:
              description: The no. of replicas for Wavefront Proxy. Defaults to 1
              format: int32
              type: integer
            token:
              description: Wavefront API Token.
              type: string
            tracePort:
              description: The port to listen on for Wavefront trace formatted data.
                Defaults to none. This is usually 30000
              format: int32
              type: integer
            traceSamplingDuration:
              description: When this is set to a value greater than 0, spans that
                are greater than or equal to this value will be sampled.
              format: double
              type: number
            traceSamplingRate:
              description: Sampling rate to apply to tracing spans sent to the proxy.
                This rate is applied to all data formats the proxy is listening on.
                Value should be between 0.0 and 1.0.  Default is 1.0
              format: double
              type: number
            url:
              description: Wavefront URL (cluster).
              type: string
            zipkinPort:
              description: The port to listen on for Zipkin formatted data. Defaults
                to none. This is usually 9411
              format: int32
              type: integer
          required:
          - url
          - token
          type: object
        status:
          properties:
            createdTimestamp:
              format: date-time
              type: string
            updatedTimestamp:
              format: date-time
              type: string
            version:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true

---

# operator_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wavefront-operator
  namespace: wavefront
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wavefront-operator
  template:
    metadata:
      labels:
        name: wavefront-operator
    spec:
      serviceAccountName: wavefront-operator
      containers:
        - name: wavefront-operator
          # Replace this with the built image name
          image: wavefronthq/wavefront-operator-for-kubernetes:0.1.0-rc3
          command:
          - wavefront-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "wavefront-operator"
---
