kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wavefront-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wavefront-logging
subjects:
- kind: ServiceAccount
  name: wavefront-logging
  namespace: wavefront