---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: wavefronts.wavefront.com
spec:
  group: wavefront.com
  names:
    kind: Wavefront
    listKind: WavefrontList
    plural: wavefronts
    singular: wavefront
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Wavefront is the Schema for the wavefronts API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: WavefrontSpec defines the desired state of Wavefront
            properties:
              clusterName:
                description: ClusterName is a unique name for the Kubernetes cluster
                  to be identified via a metric tag on Wavefront.
                type: string
              wavefrontToken:
                description: WavefrontToken is the wavefront API Token.
                type: string
              wavefrontUrl:
                description: WavefrontUrl is the wavefront instance.
                type: string
            required:
            - clusterName
            - wavefrontToken
            - wavefrontUrl
            type: object
          status:
            description: WavefrontStatus defines the observed state of Wavefront
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
